// flow-typed signature: bb47ab0596f7ef4c169a162660bfdcbc
// flow-typed version: <<STUB>>/material-ui-password-field_v^2.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-password-field'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-password-field' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-password-field/lib/PasswordField' {
  declare module.exports: any;
}

declare module 'material-ui-password-field/lib/PasswordField.spec' {
  declare module.exports: any;
}

declare module 'material-ui-password-field/src/PasswordField' {
  declare module.exports: any;
}

declare module 'material-ui-password-field/src/PasswordField.spec' {
  declare module.exports: any;
}

declare module 'material-ui-password-field/stories/index' {
  declare module.exports: any;
}

declare module 'material-ui-password-field/test/jestsetup' {
  declare module.exports: any;
}

declare module 'material-ui-password-field/test/shim' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-password-field/lib/PasswordField.js' {
  declare module.exports: $Exports<'material-ui-password-field/lib/PasswordField'>;
}
declare module 'material-ui-password-field/lib/PasswordField.spec.js' {
  declare module.exports: $Exports<'material-ui-password-field/lib/PasswordField.spec'>;
}
declare module 'material-ui-password-field/src/PasswordField.js' {
  declare module.exports: $Exports<'material-ui-password-field/src/PasswordField'>;
}
declare module 'material-ui-password-field/src/PasswordField.spec.js' {
  declare module.exports: $Exports<'material-ui-password-field/src/PasswordField.spec'>;
}
declare module 'material-ui-password-field/stories/index.js' {
  declare module.exports: $Exports<'material-ui-password-field/stories/index'>;
}
declare module 'material-ui-password-field/test/jestsetup.js' {
  declare module.exports: $Exports<'material-ui-password-field/test/jestsetup'>;
}
declare module 'material-ui-password-field/test/shim.js' {
  declare module.exports: $Exports<'material-ui-password-field/test/shim'>;
}
